In [28]:
import numpy as np

def _lower(x):
    assert x.ndim==2 # m,d
    xrow  = x[None,:,:]  # 1, m ,d
    xcol = x[:,None,:]   # m, 1, d
    mat = np.all(xrow > xcol, axis=2) # m,m
    return mat.sum(0) # m

In [29]:
import polars as pl

In [34]:
x,y = np.random.default_rng().standard_normal(size=(2, 4, 2))
print(x)
print(_lower(x))
pl.DataFrame(x, schema=list('ab')).plot.point(x='a',y='b')

[[ 1.11731287 -0.28020624]
 [ 0.52132619 -0.02939442]
 [ 0.77319851  0.09102072]
 [-0.43623994  0.69054617]]
[0 0 1 0]


alt.Chart(...)

In [35]:
def _count_low(x,y):
    assert x.ndim == y.ndim == 2
    row = x[None, :,:]
    col = y[:,None,:]
    return np.all(row > col, axis=2).sum(0)

In [36]:
_count_low(x,x)

array([0, 0, 1, 0])

In [50]:
def kol(x,y):
    dx = np.absolute(_count_low(x,y) - _count_low(x,x)).max()
    dy = np.absolute(_count_low(y,x) - _count_low(y,y)).max()
    return max(dy,dx)/x.shape[0]

In [76]:
kol(x,y)

np.float64(0.3333333333333333)

In [77]:
x,y = np.random.default_rng().standard_normal(size=(2, 3, 2))

In [78]:
import altair as alt
pl.DataFrame(x, schema=list('ab')).plot.point(x='a',y='b', color=alt.value("orange"))+ pl.DataFrame(y, schema=list('ab')).plot.point(x='a',y='b')

alt.LayerChart(...)

In [79]:
kol(y,x)

np.float64(0.3333333333333333)