# Boosting


In the context of binary classification, a weak learner is a relaxed PAC learner with a **fixed** $\varepsilon < 1/2$(i.e. just better than random guess predictor) rather than **all** $\varepsilon$. 

Boosting is a paradigm that boosts weak learners into strong PAC learners.


In [1]:
import numpy as np

In [40]:
m = 5
x = np.random.randn(m)
y = np.random.choice([-1,1], size=(m,))
z = np.hstack((x.reshape(m,1),y.reshape(m,1)))

In [41]:
z, np.argsort(z[:,0])

(array([[ 1.1907183 , -1.        ],
        [-0.20692845, -1.        ],
        [ 1.79584772,  1.        ],
        [-0.26909138,  1.        ],
        [-2.05650294, -1.        ]]),
 array([4, 3, 1, 0, 2], dtype=int64))

In [42]:
x[np.argsort(z[:,0])]

array([-2.05650294, -0.26909138, -0.20692845,  1.1907183 ,  1.79584772])

In [59]:
0.5 * np.triu(np.tri(m, k=1)) @ x[np.argsort(z[:,0])]

array([-1.16279716, -0.23800992,  0.49189492,  1.49328301,  0.89792386])

In [74]:
x.sort()
np.concatenate(([x[0]-1],x, [x[-1]+1]))

array([-3.05650294, -2.05650294, -0.26909138, -0.20692845,  1.1907183 ,
        1.79584772,  2.79584772])

In [82]:
0.5 * np.triu(np.tri(m+2, k=1))[:-1]   @ np.concatenate(([x[0]-1],x, [x[-1]+1]))

array([-2.55650294, -1.16279716, -0.23800992,  0.49189492,  1.49328301,
        2.29584772])

## decision stumps fast implementation

A decision stump is a function $h(x) = sign(x_j - \theta) b$ for some $j\in [d]$, $\theta\in\mathbb R$ and $b\in \{+,-\}$. 

In [159]:
m,d = 10,4
x = np.random.rand(m,d)
o = np.argsort(x, axis = 0) 
x, o

(array([[0.81133329, 0.10538287, 0.76382527, 0.79637636],
        [0.80977562, 0.37963735, 0.33178965, 0.61541489],
        [0.43392094, 0.91380815, 0.00389056, 0.71558217],
        [0.19678021, 0.07571888, 0.32350247, 0.65676526],
        [0.49296368, 0.86064064, 0.20644971, 0.54483702],
        [0.04405585, 0.53136119, 0.95844583, 0.15286128],
        [0.18734396, 0.82066533, 0.02124904, 0.12791465],
        [0.95483283, 0.4496789 , 0.81691841, 0.59776738],
        [0.16931889, 0.16871066, 0.66090273, 0.40179112],
        [0.5609859 , 0.06829246, 0.20921114, 0.64236863]]),
 array([[5, 9, 2, 6],
        [8, 3, 6, 5],
        [6, 0, 4, 8],
        [3, 8, 9, 4],
        [2, 1, 3, 7],
        [4, 7, 1, 1],
        [9, 5, 8, 9],
        [1, 6, 0, 3],
        [0, 4, 7, 2],
        [7, 2, 5, 0]], dtype=int64))

In [160]:
sorted_x = np.array([x[o[:,i], i] for i in range(x.shape[1])]).T

In [161]:
sorted_x

array([[0.04405585, 0.06829246, 0.00389056, 0.12791465],
       [0.16931889, 0.07571888, 0.02124904, 0.15286128],
       [0.18734396, 0.10538287, 0.20644971, 0.40179112],
       [0.19678021, 0.16871066, 0.20921114, 0.54483702],
       [0.43392094, 0.37963735, 0.32350247, 0.59776738],
       [0.49296368, 0.4496789 , 0.33178965, 0.61541489],
       [0.5609859 , 0.53136119, 0.66090273, 0.64236863],
       [0.80977562, 0.82066533, 0.76382527, 0.65676526],
       [0.81133329, 0.86064064, 0.81691841, 0.71558217],
       [0.95483283, 0.91380815, 0.95844583, 0.79637636]])

In [162]:
sorted_x[0]-1, sorted_x[-1]+1 

(array([-0.95594415, -0.93170754, -0.99610944, -0.87208535]),
 array([1.95483283, 1.91380815, 1.95844583, 1.79637636]))

In [163]:
np.vstack((sorted_x[0]-1, sorted_x, sorted_x[-1]+1 ))

array([[-0.95594415, -0.93170754, -0.99610944, -0.87208535],
       [ 0.04405585,  0.06829246,  0.00389056,  0.12791465],
       [ 0.16931889,  0.07571888,  0.02124904,  0.15286128],
       [ 0.18734396,  0.10538287,  0.20644971,  0.40179112],
       [ 0.19678021,  0.16871066,  0.20921114,  0.54483702],
       [ 0.43392094,  0.37963735,  0.32350247,  0.59776738],
       [ 0.49296368,  0.4496789 ,  0.33178965,  0.61541489],
       [ 0.5609859 ,  0.53136119,  0.66090273,  0.64236863],
       [ 0.80977562,  0.82066533,  0.76382527,  0.65676526],
       [ 0.81133329,  0.86064064,  0.81691841,  0.71558217],
       [ 0.95483283,  0.91380815,  0.95844583,  0.79637636],
       [ 1.95483283,  1.91380815,  1.95844583,  1.79637636]])

In [164]:
np.triu(np.tri(m+2, k=1))[:-1]

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.]])

In [165]:
theta = 0.5 * np.triu(np.tri(m+2, k=1))[:-1] @ np.vstack((sorted_x[0]-1, sorted_x, sorted_x[-1]+1 ))

In [168]:
theta, theta.shape

(array([[-0.45594415, -0.43170754, -0.49610944, -0.37208535],
        [ 0.10668737,  0.07200567,  0.0125698 ,  0.14038797],
        [ 0.17833143,  0.09055088,  0.11384937,  0.2773262 ],
        [ 0.19206209,  0.13704677,  0.20783043,  0.47331407],
        [ 0.31535057,  0.274174  ,  0.26635681,  0.5713022 ],
        [ 0.46344231,  0.41465812,  0.32764606,  0.60659113],
        [ 0.52697479,  0.49052005,  0.49634619,  0.62889176],
        [ 0.68538076,  0.67601326,  0.712364  ,  0.64956694],
        [ 0.81055445,  0.84065298,  0.79037184,  0.68617372],
        [ 0.88308306,  0.88722439,  0.88768212,  0.75597926],
        [ 1.45483283,  1.41380815,  1.45844583,  1.29637636]]),
 (11, 4))

In [169]:
x, x.shape

(array([[0.81133329, 0.10538287, 0.76382527, 0.79637636],
        [0.80977562, 0.37963735, 0.33178965, 0.61541489],
        [0.43392094, 0.91380815, 0.00389056, 0.71558217],
        [0.19678021, 0.07571888, 0.32350247, 0.65676526],
        [0.49296368, 0.86064064, 0.20644971, 0.54483702],
        [0.04405585, 0.53136119, 0.95844583, 0.15286128],
        [0.18734396, 0.82066533, 0.02124904, 0.12791465],
        [0.95483283, 0.4496789 , 0.81691841, 0.59776738],
        [0.16931889, 0.16871066, 0.66090273, 0.40179112],
        [0.5609859 , 0.06829246, 0.20921114, 0.64236863]]),
 (10, 4))

In [197]:
y = np.random.choice([-1,1], (m))
z = np.concatenate( (x,y.reshape(m,1)), axis = 1)
z

array([[ 0.81133329,  0.10538287,  0.76382527,  0.79637636,  1.        ],
       [ 0.80977562,  0.37963735,  0.33178965,  0.61541489, -1.        ],
       [ 0.43392094,  0.91380815,  0.00389056,  0.71558217, -1.        ],
       [ 0.19678021,  0.07571888,  0.32350247,  0.65676526,  1.        ],
       [ 0.49296368,  0.86064064,  0.20644971,  0.54483702, -1.        ],
       [ 0.04405585,  0.53136119,  0.95844583,  0.15286128,  1.        ],
       [ 0.18734396,  0.82066533,  0.02124904,  0.12791465, -1.        ],
       [ 0.95483283,  0.4496789 ,  0.81691841,  0.59776738, -1.        ],
       [ 0.16931889,  0.16871066,  0.66090273,  0.40179112, -1.        ],
       [ 0.5609859 ,  0.06829246,  0.20921114,  0.64236863,  1.        ]])

In [182]:
toy_x =  x[:,0]
toy_z = z[:,[0,-1]]
toy_theta =  theta[:,0]

In [188]:
F = np.inf
def stump(x, theta,b):
    return b*(x>theta)
stump(5,2,-1)

-1

In [202]:
[stump(val,0.1,1) for val in toy_x[y==1]] + [stump(val,0.1,-1) for val in toy_x[y==-1]]

[1, 1, 0, 1, -1, -1, -1, -1, -1, -1]

In [204]:
[val>0.5 for val in toy_x[y==1]] + [val>0.5 for val in toy_x[y==-1]]

[True, False, False, True, True, False, False, False, True, False]

In [224]:
def F(z,theta,b):
    c_pos=[(xv>theta) for xv in toy_z[toy_z[:,1]==1, 0]]
    c_neg=[(xv<=theta) for xv in toy_z[toy_z[:,1]==-1, 0]]
    c = c_pos+c_neg
    return sum(c) if b==1 else z.shape[0] - sum(c)

In [244]:
Fs = np.array([[F(toy_z,t,b) for t in toy_theta ] for b in (-1,1)])

In [245]:
np.unravel_index(np.argmin(Fs), Fs.shape)

(1, 7)

In [246]:
def best_params(z,theta):
    Fs =  np.array([[F(z,t,b) for t in theta] for b in (-1,1)])
    best_row, best_col = np.unravel_index(np.argmin(Fs), Fs.shape)
    best_b = best_row*2 -1
    best_theta = theta[best_col]
    return best_b, best_theta

In [247]:
best_params(toy_z,toy_theta)

(1, 0.685380758109065)

## putting all these together

In [253]:
m,d = 5,4
x = np.random.rand(m,d)
o = np.argsort(x, axis = 0) 
y = np.random.choice([-1,1], (m))
z = np.concatenate( (x,y.reshape(m,1)), axis = 1)
x, o, y, z

(array([[0.53948496, 0.00694566, 0.2027294 , 0.14133497],
        [0.95157251, 0.466502  , 0.98350129, 0.5551404 ],
        [0.97365429, 0.76847735, 0.4407016 , 0.88672255],
        [0.67011254, 0.9001997 , 0.20384571, 0.81875743],
        [0.97811317, 0.66123422, 0.64162618, 0.45398309]]),
 array([[0, 0, 0, 0],
        [3, 1, 3, 4],
        [1, 4, 2, 1],
        [2, 2, 4, 3],
        [4, 3, 1, 2]], dtype=int64),
 array([ 1, -1, -1,  1,  1]),
 array([[ 0.53948496,  0.00694566,  0.2027294 ,  0.14133497,  1.        ],
        [ 0.95157251,  0.466502  ,  0.98350129,  0.5551404 , -1.        ],
        [ 0.97365429,  0.76847735,  0.4407016 ,  0.88672255, -1.        ],
        [ 0.67011254,  0.9001997 ,  0.20384571,  0.81875743,  1.        ],
        [ 0.97811317,  0.66123422,  0.64162618,  0.45398309,  1.        ]]))

In [254]:
sorted_x = np.array([x[o[:,i], i] for i in range(x.shape[1])]).T
theta = 0.5 * np.triu(np.tri(m+2, k=1))[:-1] @ np.vstack((sorted_x[0]-1, sorted_x, sorted_x[-1]+1 ))
sorted_x, theta

(array([[0.53948496, 0.00694566, 0.2027294 , 0.14133497],
        [0.67011254, 0.466502  , 0.20384571, 0.45398309],
        [0.95157251, 0.66123422, 0.4407016 , 0.5551404 ],
        [0.97365429, 0.76847735, 0.64162618, 0.81875743],
        [0.97811317, 0.9001997 , 0.98350129, 0.88672255]]),
 array([[ 0.03948496, -0.49305434, -0.2972706 , -0.35866503],
        [ 0.60479875,  0.23672383,  0.20328755,  0.29765903],
        [ 0.81084252,  0.56386811,  0.32227365,  0.50456175],
        [ 0.9626134 ,  0.71485578,  0.54116389,  0.68694892],
        [ 0.97588373,  0.83433853,  0.81256374,  0.85273999],
        [ 1.47811317,  1.4001997 ,  1.48350129,  1.38672255]]))

In [258]:
def F(z,theta,b,j):
    loss_pos=[(xv>theta) for xv in z[z[:,-1]==1, j]]
    loss_neg=[(xv<=theta) for xv in z[z[:,-1]==-1, j]]
    loss = loss_pos+loss_neg
    return sum(loss) if b==1 else z.shape[0] - sum(loss)

def best_params(z,theta):
    Fs =  np.array([[F(z,t,b) for t in theta] for b in (-1,1)])
    best_row, best_col = np.unravel_index(np.argmin(Fs), Fs.shape)
    best_b = best_row*2 -1
    best_theta = theta[best_col]
    return best_b, best_theta

In [260]:
F(z,theta[0,0],1,0)

3